setwd("/Users/hongwei/Desktop")
rawdata <- read.table("emissionssw.dat",header = TRUE)
summary(rawdata)
model <- lm(nox~., data=rawdata)
summary(model)
step.model <- stepAIC(model, direction = "both",trace = FALSE)
summary(step.model)
AIC(model)
AIC(step.model)
